version: '3.1'

services:
  php:
    image: shoppinpal/php-fpm-dev:8.0-alpine
    working_dir: /var/www/html
    volumes:
    - .:/var/www/html:rw

  mysql:
    image: mysql:8.0
    environment:
      ROOT_PASSWORD: secret
